spring:
  datasource:
    url: jdbc:mysql://localhost:3306/inheritance?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: mysql
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  user:
    datasource.driver-class-name: com.mysql.jdbc.Driver
